# -*- coding: utf-8 -*-
"""Browser Control SDK API reference text."""

from __future__ import annotations


def generate_api_reference() -> str:
    """Return the SDK API reference for LLM-readable environments."""
    return """Browser Control SDK API Reference
=================================

Usage Guide
-----------
The SDK is designed for code generated by an LLM. It exposes a small
object-oriented surface over the existing Browser Control runtime.

In the Python REPL the ``browser`` variable is preloaded. If you need to
recreate it manually:

    from sdk import Browser
    browser = await Browser.connect(ws_url="<bridge-url>", token="<token>")

If a call raises ``BridgeDisconnected``, recover the preloaded object once:

    browser = await browser.connect()

This refreshes the current Browser object in place and returns it.
Do not instantiate Browser() directly; the constructor requires internal
bridge state that the REPL already manages. If the reconnect attempt still
cannot reach the bridge, stop and report a blocker instead of looping.

Core rule: observe before act. Call ``await tab.snapshot()`` before any
mutating method such as click, type, press_key, scroll, hover,
select_option, or navigate. A mutating action consumes the fresh observation,
so observe again before the next mutating action.

Synchronization rule: ``wait_for`` is not a mutating action. It may be used
after a click, navigation, scroll, or type operation to let the page settle,
but it makes any previous snapshot stale. Always call ``await tab.snapshot()``
after ``wait_for`` before the next mutating action.

Production rule: read after write. After any state-changing action, verify
state from a fresh observation or an authoritative page. Do not treat a
stale badge, local counter, or unchanged DOM as proof of success or failure.

LLM-safe call patterns:

    tab = await browser.tabs.open("https://example.com")
    snap = await tab.snapshot()
    print(snap.text)
    await tab.scroll(direction="down", amount="page")
    await tab.wait_for(2)
    snap = await tab.snapshot()

For a new user task, prefer opening a fresh SDK-owned background tab:

    tab = await browser.tabs.open("https://example.com")

Use browser.tabs.list() and browser.tabs.get(tab_id) only when the user asks
you to use, inspect, clean up, or is continuing work in a specific existing tab.
Do not mine unrelated old tabs to answer a new task unless the user asked to
reuse existing browser state.

``snapshot()`` takes no arguments; do not call ``snapshot(full=True)``.
``scroll`` only accepts keyword arguments such as ``direction`` and
``amount``. JavaScript evaluation is not available in control mode:
do not call ``tab.evaluate`` or ``tab.action("evaluate", ...)``.
Do not read or view screenshot files with local file/media tools. If a
snapshot is degraded after one wait/reload, switch to another web UI route
or report a blocker instead of repeating the same observation loop.

class Browser:
    tabs: Tabs

    async def connect(ws_url: str = "", token: str = "") -> Browser:
        Create a Browser SDK instance when called as Browser.connect(...).
        When called as browser.connect(), reconnect the existing object in
        place and return it.

    async def documentation(self) -> str:
        Return this API reference.

    async def close(self) -> None:
        Release all tabs held by this Browser instance.

class Tabs:
    async def list(self) -> list[TabInfo]:
        Return visible browser tabs as TabInfo objects.

    async def get(self, tab_id: int | Tab) -> Tab:
        Claim a browser tab and return a Tab object. Passing an existing
        Tab returns it unchanged.

    async def open(self, url: str = "about:blank") -> Tab:
        Open, claim, and attach a background tab for browser work.

    async def new_tab(self, url: str = "about:blank") -> Tab:
        Alias for open(url).

    async def new(self, url: str = "about:blank") -> Tab:
        Alias for open(url).

    async def claim(
        self,
        tab_id: int | None = None,
        url: str = "about:blank",
    ) -> Tab:
        Alias for open(url) when tab_id is omitted, otherwise get(tab_id).

    async def claim_tab(
        self,
        tab_id: int | Tab | None = None,
        url: str = "about:blank",
    ) -> Tab:
        Alias for claim(tab_id, url).

    async def current(self) -> Tab | None:
        Return the most recently claimed Tab.

class Tab:
    id: int

    async def snapshot(self) -> Snapshot:
        Observe the tab and return text plus reference metadata.
        snapshot() takes no arguments.

    async def screenshot(
        self,
        path: str = "",
        full_page: bool = False,
        screenshot_type: str = "png",
    ) -> ScreenshotResult:
        Observe the tab visually and save a screenshot. Like snapshot(),
        this is an observation and can be used before a mutating action.
        Do not read or view screenshot files with non-SDK tools.

    async def click(
        self,
        *,
        ref: str | None = None,
        selector: str | None = None,
        text: str | None = None,
        x: float | str | None = None,
        y: float | str | None = None,
    ) -> ClickResult:
        Click a target in the tab. Requires a fresh observation.

    async def type(
        self,
        text: str,
        *,
        ref: str | None = None,
        selector: str | None = None,
        submit: bool = False,
    ) -> TypeResult:
        Type text into the active or targeted element.

    async def press_key(self, key: str) -> ActionResult:
        Press a keyboard key.

    async def hover(self, **kwargs) -> ActionResult:
        Hover over a target.

    async def scroll(self, **kwargs) -> ActionResult:
        Scroll the page or a target region.
        Example: await tab.scroll(direction="down", amount="page")

    async def select_option(self, **kwargs) -> ActionResult:
        Select one or more options in a control.

    async def navigate(self, url: str) -> ActionResult:
        Navigate the claimed tab to a URL.

    async def wait_for(self, **kwargs) -> ActionResult:
        Wait for page state. Does not require a fresh observation, but makes
        any previous observation stale; call snapshot() after it before
        clicking, typing, scrolling, selecting, or navigating again. A single
        positional number is accepted as seconds, or milliseconds when the
        value is greater than 100.
        Examples: await tab.wait_for(2) or await tab.wait_for(wait_time=2).

    async def close(self, force: bool = False) -> ActionResult:
        Close a Tab created by the SDK. Tabs claimed from the user's existing
        browser are released by default; pass force=True only when the user
        explicitly asked to close that tab.

class Snapshot:
    text: str
    refs: dict[str, RefInfo]
    degraded: bool
    str(snapshot), snapshot[:N], and snapshot.text expose the text content.

class ScreenshotResult:
    ok: bool
    needs_observation: bool
    message: str
    path: str

class RefInfo:
    role: str
    name: str
    x: float
    y: float
    bounds: tuple[float, float, float, float] | None

class ClickResult:
    ok: bool
    navigation_occurred: bool
    url: str
    needs_observation: bool
    message: str

class TypeResult:
    ok: bool
    needs_observation: bool
    message: str

class ActionResult:
    ok: bool
    needs_observation: bool
    message: str

class TabInfo:
    id: int
    url: str
    title: str

Errors
------
ObservationRequired:
    Raised when a mutating method is called without a fresh snapshot.
TabOccupied:
    Raised when another holder owns the tab lease.
StaleLease:
    Raised when a lease version is outdated.
BridgeDisconnected:
    Raised when the Chrome extension bridge is disconnected.
"""


__all__ = ["generate_api_reference"]
