# -*- coding: utf-8 -*-
"""Browser Control SDK API reference text."""

from __future__ import annotations


def generate_api_reference() -> str:
    """Return the SDK API reference for LLM-readable environments."""
    return """Browser Control SDK API Reference
=================================

Usage Guide
-----------
The SDK is designed for code generated by an LLM. It exposes a small
object-oriented surface over the existing Browser Control runtime.

In the Python REPL the ``browser`` variable is preloaded. If you need to
recreate it manually:

    from sdk import Browser
    browser = await Browser.connect(ws_url="<bridge-url>", token="<token>")

If a call raises ``BridgeDisconnected``, recover the preloaded object once:

    browser = await browser.connect()

This refreshes the current Browser object in place and returns it.
Do not instantiate Browser() directly; the constructor requires internal
bridge state that the REPL already manages. If the reconnect attempt still
cannot reach the bridge, stop and report a blocker instead of looping.

Core rule: observe before act. Call ``await tab.snapshot()`` before any
mutating method such as click, type, press_key, scroll, hover,
select_option, or navigate. A mutating action consumes the fresh observation,
so observe again before the next mutating action.

Synchronization rule: ``wait_for`` is not a mutating action. It may be used
after a click, navigation, scroll, or type operation to let the page settle,
but it makes any previous snapshot stale. Always call ``await tab.snapshot()``
after ``wait_for`` before the next mutating action.
Opening a new tab does not count as an observation. After
``browser.tabs.open(...)``, call ``await tab.snapshot()`` before scrolling,
clicking, typing, or selecting.

Production rule: read after write. After any state-changing action, verify
state from a fresh observation or an authoritative page. Do not treat a
stale badge, local counter, or unchanged DOM as proof of success or failure.
Treat an authoritative state page as a subtask boundary. For example, if a
cart/status/list page shows an item or setting that satisfies the user's
requested quantity/category, advance to the next requested subtask; do not
add another item, repeat the same write, or return to search unless the user
explicitly asked for more.

LLM-safe call patterns:

    tab = await browser.tabs.open("https://example.com")
    snap = await tab.snapshot()
    print(snap.text)
    await tab.click(ref="r1_e22")
    await tab.scroll(direction="down", amount="page")
    await tab.wait_for(2)
    snap = await tab.snapshot()
    await tab.scroll(direction="up", amount="top")
    snap = await tab.snapshot()

For a new user task, prefer opening a fresh SDK-owned background tab:

    tab = await browser.tabs.open("https://example.com")

Prefer direct browser-visible routes when the user intent can be expressed as
a URL, such as a search page, list page, detail page, cart page, or status
page. Do not start from a homepage and type into a search box when an
equivalent URL route is available.

Use browser.tabs.list() and browser.tabs.get(tab_id) only for tabs already
managed by this SDK session. Use browser.tabs.list(all=True) only when the
user asks you to use, inspect, clean up, or continue existing browser state.
This includes continuing work in a specific existing tab. Do not mine
unrelated old tabs to answer a new task unless the user asked to reuse
existing browser state.

Keep each browser cell narrow: perform at most one mutating browser action,
optionally wait for it to settle, then take a fresh snapshot. Do not batch
click/type/click sequences in one ``python_repl`` cell. If a click, type,
selection, or form-submit action times out or leaves the page unchanged,
retry that exact action sequence at most once after a fresh snapshot. On the
next failure, change route: use a direct URL, a canonical list/detail/status
page, a different visible control, or report a real blocker when page
evidence requires it.

When a control label is known but the snapshot is truncated or misses the
control, try ``await tab.click(text="visible label")`` before CSS selectors
or coordinates. The SDK text locator can find visible DOM text and scroll
offscreen controls into view. Use selectors only when they are stable and
semantic; avoid guessed class names.

Coordinate rule: ``tab.click(x=..., y=...)`` uses viewport CSS pixels, not
raw screenshot pixels and not the scaled image shown in the chat UI. When
``tab.screenshot()`` returns a ``coordinate_space`` payload, convert visual
image coordinates first:

    click_x = image_x * coordinate_space["image_to_viewport_scale_x"]
    click_y = image_y * coordinate_space["image_to_viewport_scale_y"]

Coordinates outside ``0..viewport_width`` and ``0..viewport_height`` are
invalid. If a coordinate click reports no navigation, no state change, or an
out-of-viewport error, do not repeat the same nearby point; choose a
different target from fresh evidence, use a semantic route, or report a real
blocker.

For product-selection or shopping tasks, treat each listing as a candidate.
If the current candidate lacks the required purchase/cart action, return to
the listing and try a bounded set of different real candidates or filters
before declaring the task blocked. Use only real hrefs/refs observed from
the page; do not invent item ids, API URLs, cart URLs, or mobile detail
links.

Snapshot refs are snapshot-scoped string identifiers. Use the complete quoted
ref exactly as shown in the latest snapshot, such as
``await tab.click(ref="r3_e22")``. Do not strip the ``r3_`` prefix, invent a
shorter ``e22`` ref, or reuse a ref copied from an older snapshot. Link refs
may include an href used by the SDK for reliable same-tab navigation. The REPL
also prebinds common ref symbols to tolerate copied snippets, but quoted
strings copied from the latest snapshot are the clearest form.

``snapshot()`` takes no arguments; do not call ``snapshot(full=True)``.
``scroll`` only accepts keyword arguments such as ``direction`` and
``amount``. Use ``amount="top"`` or ``amount="bottom"`` for absolute jumps
when the relevant control is expected near the start or end of a long page.
Snapshot text may begin with ``page_state`` containing ``scroll_percent``,
``at_top``, and ``at_bottom``; use it to avoid repeated ineffective scrolls.
Snapshot text may also include ``action_target`` lines for visible controls
that modern pages expose poorly through accessibility trees. If an
``action_target`` line has a ``[ref=...]`` value such as ``[ref=r4_e17]``,
click that complete quoted ref first. If it does not have a ref, prefer its
text with ``await tab.click(text="...")``; use x/y coordinates only when ref
and text targeting both fail.
Icon-only controls may appear with synthesized labels such as ``add cart``,
``cart``, or ``buy`` when the DOM exposes that semantic through stable
attributes. Prefer those refs over visual coordinate guesses. If a
synthesized icon label appears without a ref, use text targeting such as
``await tab.click(text="add cart")``; the SDK resolves that label from stable
element attributes instead of guessed coordinates.
Use an action candidate budget: once the current page exposes a plausible
next action such as add-to-cart, buy, checkout, confirm, delete, or search,
try the strongest ref/text candidate within the next browser action. If it
fails after one fresh observation, try a different real candidate or route.
Do not keep inspecting listings, screenshots, or broad page snapshots while
a page-level action target already matches the task.
JavaScript evaluation is not available in control mode:
do not call ``tab.evaluate`` or ``tab.action("evaluate", ...)``.
Do not read or view screenshot files with local file/media tools. If a
snapshot is degraded after one wait/reload, switch to another web UI route
or report a blocker instead of repeating the same observation loop.

class Browser:
    tabs: Tabs

    async def connect(ws_url: str = "", token: str = "") -> Browser:
        Create a Browser SDK instance when called as Browser.connect(...).
        When called as browser.connect(), reconnect the existing object in
        place and return it.

    async def documentation(self) -> str:
        Return this API reference.

    async def close(self) -> None:
        Release all tabs held by this Browser instance.

class Tabs:
    async def list(self, *, all: bool = False) -> list[TabInfo]:
        Return SDK-managed tabs as TabInfo objects. Pass all=True only when
        the user explicitly needs the full visible Chrome tab list.

    async def get(self, tab_id: int | Tab) -> Tab:
        Claim a browser tab and return a Tab object. Passing an existing
        Tab returns it unchanged.

    async def open(self, url: str = "about:blank") -> Tab:
        Open, claim, and attach a background tab for browser work.

    async def new_tab(self, url: str = "about:blank") -> Tab:
        Alias for open(url).

    async def new(self, url: str = "about:blank") -> Tab:
        Alias for open(url).

    async def claim(
        self,
        tab_id: int | None = None,
        url: str = "about:blank",
    ) -> Tab:
        Alias for open(url) when tab_id is omitted, otherwise get(tab_id).

    async def claim_tab(
        self,
        tab_id: int | Tab | None = None,
        url: str = "about:blank",
    ) -> Tab:
        Alias for claim(tab_id, url).

    async def current(self) -> Tab | None:
        Return the most recently claimed Tab.

    async def close(
        self,
        tab_id: int | Tab | None = None,
        force: bool = False,
    ) -> ActionResult:
        Close or release a tab. Passing no tab_id closes the current tab.
        Signature shorthand: ``async def close(self, tab_id=None, ...)``.
        Use ``await tab.close()`` or ``await browser.tabs.close(tab_id)``;
        there is no separate ``browser.tabs.close_tab`` method.

class Tab:
    id: int

    async def snapshot(self) -> Snapshot:
        Observe the tab and return text plus reference metadata.
        snapshot() takes no arguments.

    async def screenshot(
        self,
        path: str = "",
        full_page: bool = False,
        screenshot_type: str = "png",
    ) -> ScreenshotResult:
        Observe the tab visually and save a screenshot. Like snapshot(),
        this is an observation and can be used before a mutating action.
        Do not read or view screenshot files with non-SDK tools.

    async def click(
        self,
        *,
        ref: str | None = None,
        selector: str | None = None,
        text: str | None = None,
        x: float | str | None = None,
        y: float | str | None = None,
    ) -> ClickResult:
        Click a target in the tab. Requires a fresh observation.

    async def type(
        self,
        text: str,
        *,
        ref: str | None = None,
        selector: str | None = None,
        submit: bool = False,
    ) -> TypeResult:
        Type text into the active or targeted element.

    async def press_key(self, key: str) -> ActionResult:
        Press a keyboard key.

    async def hover(self, **kwargs) -> ActionResult:
        Hover over a target.

    async def scroll(self, **kwargs) -> ActionResult:
        Scroll the page or a target region.
        Example: await tab.scroll(direction="down", amount="page")
        Absolute jumps: await tab.scroll(direction="up", amount="top") or
        await tab.scroll(direction="down", amount="bottom").

    async def select_option(self, **kwargs) -> ActionResult:
        Select one or more options in a control.

    async def navigate(self, url: str) -> ActionResult:
        Navigate the claimed tab to a URL.

    async def wait_for(self, **kwargs) -> ActionResult:
        Wait for page state. Does not require a fresh observation, but makes
        any previous observation stale; call snapshot() after it before
        clicking, typing, scrolling, selecting, or navigating again. A single
        positional number is accepted as seconds, or milliseconds when the
        value is greater than 100.
        Examples: await tab.wait_for(2) or await tab.wait_for(wait_time=2).

    async def close(self, force: bool = False) -> ActionResult:
        Close a Tab created by the SDK. Tabs claimed from the user's existing
        browser are released by default; pass force=True only when the user
        explicitly asked to close that tab.

class Snapshot:
    text: str
    refs: dict[str, RefInfo]
    degraded: bool
    str(snapshot), snapshot[:N], snapshot.text, snapshot.splitlines(), and
    other common text helpers expose the text content.

class ScreenshotResult:
    ok: bool
    needs_observation: bool
    message: str
    path: str
    coordinate_space: dict[str, Any]

class RefInfo:
    role: str
    name: str
    x: float
    y: float
    bounds: tuple[float, float, float, float] | None
    href: str
    target: str

class ClickResult:
    ok: bool
    navigation_occurred: bool
    url: str
    needs_observation: bool
    message: str

class TypeResult:
    ok: bool
    needs_observation: bool
    message: str

class ActionResult:
    ok: bool
    needs_observation: bool
    message: str

class TabInfo:
    id: int
    url: str
    title: str

Errors
------
ObservationRequired:
    Raised when a mutating method is called without a fresh snapshot.
TabOccupied:
    Raised when another holder owns the tab lease.
StaleLease:
    Raised when a lease version is outdated.
BridgeDisconnected:
    Raised when the Chrome extension bridge is disconnected.
"""


__all__ = ["generate_api_reference"]
